export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT'
export const REQUEST_TOP = 'REQUEST_TOP'
export const REQUEST_DETAIL = 'REQUEST_DETAIL'
export const RECEIVE_DETAIL = 'RECEIVE_DETAIL'
export const INVALIDATE_DETAIL = 'INVALIDATE_DETAIL'
export const REQUEST_COM = 'REQUEST_COM'
export const RECEIVE_COM = 'RECEIVE_COM'
export const INVALIDATE_COM = 'INVALIDATE_COM'
export const REQUEST_CAT = 'REQUEST_CAT'
export const RECEIVE_CAT = 'RECEIVE_CAT'
export const REQUEST_AFTERCAT = 'REQUEST_AFTERCAT'
export const RECEIVE_AFTERCAT = 'RECEIVE_AFTERCAT'
export const INVALIDATE_AFTERCAT = 'INVALIDATE_AFTERCAT'
export const REQUEST_AFTER = 'REQUEST_AFTER'
export const RECEIVE_AFTER = 'RECEIVE_AFTER'
export const INVALIDATE_AFTER = 'INVALIDATE_AFTER'

